// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/v3/pkg/models/shared"
	"net/http"
)

type CreateDomainResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Details about the newly added domain.
	CreateDomainResult *shared.CreateDomainResult
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateDomainResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateDomainResponse) GetCreateDomainResult() *shared.CreateDomainResult {
	if o == nil {
		return nil
	}
	return o.CreateDomainResult
}

func (o *CreateDomainResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateDomainResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
