// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"net/http"
)

type DeleteLogSinkRequest struct {
	LogSinkID string `pathParam:"style=simple,explode=false,name=logSinkId"`
}

func (o *DeleteLogSinkRequest) GetLogSinkID() string {
	if o == nil {
		return ""
	}
	return o.LogSinkID
}

type DeleteLogSinkResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The operation was performed successfully.
	SuccessResult *shared.SuccessResult
}

func (o *DeleteLogSinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteLogSinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteLogSinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteLogSinkResponse) GetSuccessResult() *shared.SuccessResult {
	if o == nil {
		return nil
	}
	return o.SuccessResult
}
