// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/v3/pkg/models/shared"
	"net/http"
)

type DeleteCDNRequest struct {
	// Request body
	CDNRequest shared.CDNRequest `request:"mediaType=application/json"`
	Domain     string            `pathParam:"style=simple,explode=false,name=domain"`
	Subdomain  string            `pathParam:"style=simple,explode=false,name=subdomain"`
}

func (o *DeleteCDNRequest) GetCDNRequest() shared.CDNRequest {
	if o == nil {
		return shared.CDNRequest{}
	}
	return o.CDNRequest
}

func (o *DeleteCDNRequest) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *DeleteCDNRequest) GetSubdomain() string {
	if o == nil {
		return ""
	}
	return o.Subdomain
}

type DeleteCDNResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The operation was performed successfully.
	SuccessResult *shared.SuccessResult
}

func (o *DeleteCDNResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteCDNResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteCDNResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteCDNResponse) GetSuccessResult() *shared.SuccessResult {
	if o == nil {
		return nil
	}
	return o.SuccessResult
}
