// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"net/http"
)

type GenerateVCSTokenRequest struct {
	CustomVCSID string `pathParam:"style=simple,explode=false,name=customVCSId"`
	VcsLinkID   string `pathParam:"style=simple,explode=false,name=vcsLinkId"`
}

func (o *GenerateVCSTokenRequest) GetCustomVCSID() string {
	if o == nil {
		return ""
	}
	return o.CustomVCSID
}

func (o *GenerateVCSTokenRequest) GetVcsLinkID() string {
	if o == nil {
		return ""
	}
	return o.VcsLinkID
}

type GenerateVCSTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A version control access token for the provided link.
	VCSTokenResult *shared.VCSTokenResult
}

func (o *GenerateVCSTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateVCSTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateVCSTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenerateVCSTokenResponse) GetVCSTokenResult() *shared.VCSTokenResult {
	if o == nil {
		return nil
	}
	return o.VCSTokenResult
}
