// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"github.com/speakeasy-sdks/northflank-go/pkg/utils"
	"net/http"
)

type GetBranchesRequest struct {
	Cursor          *string `queryParam:"style=form,explode=true,name=cursor"`
	PerPage         *int64  `default:"50" queryParam:"style=form,explode=true,name=per_page"`
	RepositoryName  string  `pathParam:"style=simple,explode=false,name=repositoryName"`
	RepositoryOwner string  `pathParam:"style=simple,explode=false,name=repositoryOwner"`
	VcsService      string  `pathParam:"style=simple,explode=false,name=vcsService"`
}

func (g GetBranchesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetBranchesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetBranchesRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *GetBranchesRequest) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *GetBranchesRequest) GetRepositoryName() string {
	if o == nil {
		return ""
	}
	return o.RepositoryName
}

func (o *GetBranchesRequest) GetRepositoryOwner() string {
	if o == nil {
		return ""
	}
	return o.RepositoryOwner
}

func (o *GetBranchesRequest) GetVcsService() string {
	if o == nil {
		return ""
	}
	return o.VcsService
}

type GetBranchesResponse struct {
	// The list of branches.
	BranchesResult *shared.BranchesResult
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetBranchesResponse) GetBranchesResult() *shared.BranchesResult {
	if o == nil {
		return nil
	}
	return o.BranchesResult
}

func (o *GetBranchesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetBranchesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetBranchesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
