// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"net/http"
)

type GetCloudProvidersResponse struct {
	// A list of supported cloud providers.
	CloudProvidersResult *shared.CloudProvidersResult
	ContentType          string
	StatusCode           int
	RawResponse          *http.Response
}

func (o *GetCloudProvidersResponse) GetCloudProvidersResult() *shared.CloudProvidersResult {
	if o == nil {
		return nil
	}
	return o.CloudProvidersResult
}

func (o *GetCloudProvidersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCloudProvidersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCloudProvidersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
