// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"github.com/speakeasy-sdks/northflank-go/pkg/utils"
	"net/http"
)

type GetIntegrationsRequest struct {
	Cursor  *string `queryParam:"style=form,explode=true,name=cursor"`
	Page    *int64  `queryParam:"style=form,explode=true,name=page"`
	PerPage *int64  `default:"50" queryParam:"style=form,explode=true,name=per_page"`
}

func (g GetIntegrationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetIntegrationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetIntegrationsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *GetIntegrationsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetIntegrationsRequest) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type GetIntegrationsResponse struct {
	ContentType string
	// A list of integrations for the authenticated user
	ListIntegrationsResult *shared.ListIntegrationsResult
	StatusCode             int
	RawResponse            *http.Response
}

func (o *GetIntegrationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIntegrationsResponse) GetListIntegrationsResult() *shared.ListIntegrationsResult {
	if o == nil {
		return nil
	}
	return o.ListIntegrationsResult
}

func (o *GetIntegrationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIntegrationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
