// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"net/http"
)

type GetLogSinkRequest struct {
	LogSinkID string `pathParam:"style=simple,explode=false,name=logSinkId"`
}

func (o *GetLogSinkRequest) GetLogSinkID() string {
	if o == nil {
		return ""
	}
	return o.LogSinkID
}

type GetLogSinkResponse struct {
	ContentType string
	// Details about a log sink.
	LogSinkDetails *shared.LogSinkDetails
	StatusCode     int
	RawResponse    *http.Response
}

func (o *GetLogSinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetLogSinkResponse) GetLogSinkDetails() *shared.LogSinkDetails {
	if o == nil {
		return nil
	}
	return o.LogSinkDetails
}

func (o *GetLogSinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetLogSinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
