// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/v3/pkg/models/shared"
	"net/http"
)

type GetRegistryRequest struct {
	CredentialID string `pathParam:"style=simple,explode=false,name=credentialId"`
}

func (o *GetRegistryRequest) GetCredentialID() string {
	if o == nil {
		return ""
	}
	return o.CredentialID
}

type GetRegistryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Data about the registry credentials.
	RegistryResult *shared.RegistryResult
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRegistryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRegistryResponse) GetRegistryResult() *shared.RegistryResult {
	if o == nil {
		return nil
	}
	return o.RegistryResult
}

func (o *GetRegistryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRegistryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
