// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/models/shared"
	"net/http"
)

type ListAddonTypesResponse struct {
	// A list of the available addon types.
	AddonTypesResult *shared.AddonTypesResult
	ContentType      string
	StatusCode       int
	RawResponse      *http.Response
}

func (o *ListAddonTypesResponse) GetAddonTypesResult() *shared.AddonTypesResult {
	if o == nil {
		return nil
	}
	return o.AddonTypesResult
}

func (o *ListAddonTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListAddonTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListAddonTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
