// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/v3/pkg/models/shared"
	"github.com/speakeasy-sdks/northflank-go/v3/pkg/utils"
	"net/http"
)

type ListDomainsRequest struct {
	Cursor  *string `queryParam:"style=form,explode=true,name=cursor"`
	Page    *int64  `queryParam:"style=form,explode=true,name=page"`
	PerPage *int64  `default:"50" queryParam:"style=form,explode=true,name=per_page"`
}

func (l ListDomainsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDomainsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListDomainsRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListDomainsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListDomainsRequest) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type ListDomainsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of domains registered to this account.
	ListDomainsResult *shared.ListDomainsResult
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListDomainsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDomainsResponse) GetListDomainsResult() *shared.ListDomainsResult {
	if o == nil {
		return nil
	}
	return o.ListDomainsResult
}

func (o *ListDomainsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDomainsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
