// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/northflank-go/v3/pkg/models/shared"
	"net/http"
)

type UpdateLogSinkRequest struct {
	// Request body
	LogSinkRequest shared.LogSinkRequest `request:"mediaType=application/json"`
	LogSinkID      string                `pathParam:"style=simple,explode=false,name=logSinkId"`
}

func (o *UpdateLogSinkRequest) GetLogSinkRequest() shared.LogSinkRequest {
	if o == nil {
		return shared.LogSinkRequest{}
	}
	return o.LogSinkRequest
}

func (o *UpdateLogSinkRequest) GetLogSinkID() string {
	if o == nil {
		return ""
	}
	return o.LogSinkID
}

type UpdateLogSinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The operation was performed successfully.
	SuccessResult *shared.SuccessResult
}

func (o *UpdateLogSinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateLogSinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateLogSinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateLogSinkResponse) GetSuccessResult() *shared.SuccessResult {
	if o == nil {
		return nil
	}
	return o.SuccessResult
}
