// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/northflank-go/pkg/utils"
)

// AddRegistryType1Provider - The registry provider associated with this set of credentials.
type AddRegistryType1Provider string

const (
	AddRegistryType1ProviderDockerhub AddRegistryType1Provider = "dockerhub"
	AddRegistryType1ProviderGcr       AddRegistryType1Provider = "gcr"
	AddRegistryType1ProviderGcrEu     AddRegistryType1Provider = "gcr-eu"
	AddRegistryType1ProviderGcrUs     AddRegistryType1Provider = "gcr-us"
	AddRegistryType1ProviderGitlab    AddRegistryType1Provider = "gitlab"
	AddRegistryType1ProviderGithub    AddRegistryType1Provider = "github"
	AddRegistryType1ProviderCustom    AddRegistryType1Provider = "custom"
)

func (e AddRegistryType1Provider) ToPointer() *AddRegistryType1Provider {
	return &e
}

func (e *AddRegistryType1Provider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dockerhub":
		fallthrough
	case "gcr":
		fallthrough
	case "gcr-eu":
		fallthrough
	case "gcr-us":
		fallthrough
	case "gitlab":
		fallthrough
	case "github":
		fallthrough
	case "custom":
		*e = AddRegistryType1Provider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddRegistryType1Provider: %v", v)
	}
}

// AddRegistryType1Restrictions - Data about whether the credentials are restricted to certain projects.
type AddRegistryType1Restrictions struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// An array of projects the credentials are restricted to, if applicable.
	Projects []string `json:"projects,omitempty"`
	// Whether the credentials are restricted to specific projects.
	Restricted *bool `default:"false" json:"restricted"`
}

func (a AddRegistryType1Restrictions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddRegistryType1Restrictions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *AddRegistryType1Restrictions) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *AddRegistryType1Restrictions) GetProjects() []string {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *AddRegistryType1Restrictions) GetRestricted() *bool {
	if o == nil {
		return nil
	}
	return o.Restricted
}

type AddRegistryType1 struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// Description of the credentials.
	Description string `json:"description"`
	// Name of the credentials.
	Name string `json:"name"`
	// Password, Personal Access Token, or API key for the container registry.
	Password string `json:"password"`
	// The registry provider associated with this set of credentials.
	Provider AddRegistryType1Provider `json:"provider"`
	// Custom url for the container registry. Only usable (and required) when `provider` is `custom`.
	RegistryURL *string `json:"registryUrl,omitempty"`
	// Data about whether the credentials are restricted to certain projects.
	Restrictions *AddRegistryType1Restrictions `json:"restrictions,omitempty"`
	// Username for the container registry.
	Username string `json:"username"`
}

func (a AddRegistryType1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddRegistryType1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *AddRegistryType1) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *AddRegistryType1) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *AddRegistryType1) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AddRegistryType1) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *AddRegistryType1) GetProvider() AddRegistryType1Provider {
	if o == nil {
		return AddRegistryType1Provider("")
	}
	return o.Provider
}

func (o *AddRegistryType1) GetRegistryURL() *string {
	if o == nil {
		return nil
	}
	return o.RegistryURL
}

func (o *AddRegistryType1) GetRestrictions() *AddRegistryType1Restrictions {
	if o == nil {
		return nil
	}
	return o.Restrictions
}

func (o *AddRegistryType1) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
