// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Data - Result data.
type Data struct {
	// The content to set the DNS record to
	Content string `json:"content"`
	// The full domain name with subdomain
	FullName string `json:"fullName"`
	// The subdomain.
	Name string `json:"name"`
	// The record type to use for the DNS record to verify the subdomain - always CNAME for subdomains.
	RecordType string `json:"recordType"`
	// Whether the subdomain has been verified successfully and can be used.
	Verified bool `json:"verified"`
}

func (o *Data) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *Data) GetFullName() string {
	if o == nil {
		return ""
	}
	return o.FullName
}

func (o *Data) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Data) GetRecordType() string {
	if o == nil {
		return ""
	}
	return o.RecordType
}

func (o *Data) GetVerified() bool {
	if o == nil {
		return false
	}
	return o.Verified
}

// AddSubDomainResult - Response object.
type AddSubDomainResult struct {
	// Result data.
	Data Data `json:"data"`
}

func (o *AddSubDomainResult) GetData() Data {
	if o == nil {
		return Data{}
	}
	return o.Data
}
