// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/utils"
)

type APIErrorResultData struct {
}

// APIErrorResult - API Error response model
type APIErrorResult struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// Error code
	Code string              `json:"code"`
	Data *APIErrorResultData `json:"data,omitempty"`
	// Error description
	Message string `json:"message"`
	// Status code
	Status float32 `json:"status"`
}

func (a APIErrorResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIErrorResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *APIErrorResult) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *APIErrorResult) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *APIErrorResult) GetData() *APIErrorResultData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *APIErrorResult) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *APIErrorResult) GetStatus() float32 {
	if o == nil {
		return 0.0
	}
	return o.Status
}
