// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CloudProvidersResultDataProvidersFlags - An object with feature flags to indicate (un)supported features
type CloudProvidersResultDataProvidersFlags struct {
	// Node pool autoscaling support
	Autoscaling *bool `json:"autoscaling,omitempty"`
	// Preemptible/Spot node pool support
	Preemptible *bool `json:"preemptible,omitempty"`
}

func (o *CloudProvidersResultDataProvidersFlags) GetAutoscaling() *bool {
	if o == nil {
		return nil
	}
	return o.Autoscaling
}

func (o *CloudProvidersResultDataProvidersFlags) GetPreemptible() *bool {
	if o == nil {
		return nil
	}
	return o.Preemptible
}

// CloudProvidersResultDataProviders - A provider object
type CloudProvidersResultDataProviders struct {
	// An array of supported node disk sizes
	DiskSizes []float32 `json:"diskSizes"`
	// The kubernetes engine used.
	Engine string `json:"engine"`
	// An object with feature flags to indicate (un)supported features
	Flags CloudProvidersResultDataProvidersFlags `json:"flags"`
	// The ID of the provider.
	ID string `json:"id"`
	// An array of available kubernetes versions
	KubernetesVersions []string `json:"kubernetesVersions"`
	// The name of the provider.
	Name string `json:"name"`
	// An array of supported node types
	NodeTypes []string `json:"nodeTypes"`
	// An array of available regions
	Regions []string `json:"regions"`
}

func (o *CloudProvidersResultDataProviders) GetDiskSizes() []float32 {
	if o == nil {
		return []float32{}
	}
	return o.DiskSizes
}

func (o *CloudProvidersResultDataProviders) GetEngine() string {
	if o == nil {
		return ""
	}
	return o.Engine
}

func (o *CloudProvidersResultDataProviders) GetFlags() CloudProvidersResultDataProvidersFlags {
	if o == nil {
		return CloudProvidersResultDataProvidersFlags{}
	}
	return o.Flags
}

func (o *CloudProvidersResultDataProviders) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CloudProvidersResultDataProviders) GetKubernetesVersions() []string {
	if o == nil {
		return []string{}
	}
	return o.KubernetesVersions
}

func (o *CloudProvidersResultDataProviders) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CloudProvidersResultDataProviders) GetNodeTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.NodeTypes
}

func (o *CloudProvidersResultDataProviders) GetRegions() []string {
	if o == nil {
		return []string{}
	}
	return o.Regions
}

// CloudProvidersResultData - Result data.
type CloudProvidersResultData struct {
	// An array of supported cloud providers
	Providers []CloudProvidersResultDataProviders `json:"providers"`
}

func (o *CloudProvidersResultData) GetProviders() []CloudProvidersResultDataProviders {
	if o == nil {
		return []CloudProvidersResultDataProviders{}
	}
	return o.Providers
}

// CloudProvidersResult - Response object.
type CloudProvidersResult struct {
	// Result data.
	Data CloudProvidersResultData `json:"data"`
}

func (o *CloudProvidersResult) GetData() CloudProvidersResultData {
	if o == nil {
		return CloudProvidersResultData{}
	}
	return o.Data
}
