// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/northflank-go/v2/pkg/utils"
	"time"
)

// ClustersResultAutoscaling - Auto scaling settings to use for the node pool. Requires that the cloud provider supports this feature.
type ClustersResultAutoscaling struct {
	Enabled *bool  `default:"false" json:"enabled"`
	Max     *int64 `json:"max,omitempty"`
	Min     *int64 `json:"min,omitempty"`
}

func (c ClustersResultAutoscaling) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersResultAutoscaling) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ClustersResultAutoscaling) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *ClustersResultAutoscaling) GetMax() *int64 {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *ClustersResultAutoscaling) GetMin() *int64 {
	if o == nil {
		return nil
	}
	return o.Min
}

// ClustersResultLabels - Set of label keys and values that can be used to determine scheduling via resource tags.
type ClustersResultLabels struct {
}

type ClustersResultNodePools struct {
	// Auto scaling settings to use for the node pool. Requires that the cloud provider supports this feature.
	Autoscaling *ClustersResultAutoscaling `json:"autoscaling,omitempty"`
	// Zones in which the node pool should be provisioned.
	AvailabilityZones []string `json:"availabilityZones,omitempty"`
	// Disk size in GB
	DiskSize int64 `json:"diskSize"`
	// The disk type to use.
	DiskType *string `json:"diskType,omitempty"`
	// ID of existing node pool. Must be passed when modifying existing node pools. Not relevant for new node pools
	ID *string `json:"id,omitempty"`
	// Set of label keys and values that can be used to determine scheduling via resource tags.
	Labels *ClustersResultLabels `json:"labels,omitempty"`
	// Number of nodes to the node pool should be provisioned with.
	NodeCount int64 `json:"nodeCount"`
	// Machine type to be used by the node pool.
	NodeType string `json:"nodeType"`
	// Configures node pool with preemptible / spot instances if enabled.
	Preemptible *bool `default:"false" json:"preemptible"`
	// When 'provider' is 'azure', at least one system node pool is required per cluster.
	SystemPool *bool `json:"systemPool,omitempty"`
}

func (c ClustersResultNodePools) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersResultNodePools) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ClustersResultNodePools) GetAutoscaling() *ClustersResultAutoscaling {
	if o == nil {
		return nil
	}
	return o.Autoscaling
}

func (o *ClustersResultNodePools) GetAvailabilityZones() []string {
	if o == nil {
		return nil
	}
	return o.AvailabilityZones
}

func (o *ClustersResultNodePools) GetDiskSize() int64 {
	if o == nil {
		return 0
	}
	return o.DiskSize
}

func (o *ClustersResultNodePools) GetDiskType() *string {
	if o == nil {
		return nil
	}
	return o.DiskType
}

func (o *ClustersResultNodePools) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ClustersResultNodePools) GetLabels() *ClustersResultLabels {
	if o == nil {
		return nil
	}
	return o.Labels
}

func (o *ClustersResultNodePools) GetNodeCount() int64 {
	if o == nil {
		return 0
	}
	return o.NodeCount
}

func (o *ClustersResultNodePools) GetNodeType() string {
	if o == nil {
		return ""
	}
	return o.NodeType
}

func (o *ClustersResultNodePools) GetPreemptible() *bool {
	if o == nil {
		return nil
	}
	return o.Preemptible
}

func (o *ClustersResultNodePools) GetSystemPool() *bool {
	if o == nil {
		return nil
	}
	return o.SystemPool
}

type ClustersResultState struct {
	State          *string    `json:"state,omitempty"`
	TransitionTime *time.Time `json:"transitionTime,omitempty"`
}

func (c ClustersResultState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersResultState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ClustersResultState) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *ClustersResultState) GetTransitionTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.TransitionTime
}

type ClustersResultStatus struct {
	NextUpdateAfter *time.Time           `json:"nextUpdateAfter,omitempty"`
	State           *ClustersResultState `json:"state,omitempty"`
}

func (c ClustersResultStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClustersResultStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ClustersResultStatus) GetNextUpdateAfter() *time.Time {
	if o == nil {
		return nil
	}
	return o.NextUpdateAfter
}

func (o *ClustersResultStatus) GetState() *ClustersResultState {
	if o == nil {
		return nil
	}
	return o.State
}

// Clusters - A cluster object.
type Clusters struct {
	// The time the cluster was created.
	CreatedAt time.Time `json:"createdAt"`
	// Indicates if provider resource deletion has been requested by the user.
	DeletionRequested bool `json:"deletionRequested"`
	// A short description of the cluster.
	Description *string `json:"description,omitempty"`
	// Identifier for the cluster.
	ID string `json:"id"`
	// ID of the provider integration used by this cluster.
	IntegrationID string `json:"integrationId"`
	// The name of the cluster.
	Name      string                  `json:"name"`
	NodePools ClustersResultNodePools `json:"nodePools"`
	// The cloud provider to which this cluster belongs to.
	Provider *string               `json:"provider,omitempty"`
	Status   *ClustersResultStatus `json:"status,omitempty"`
}

func (c Clusters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Clusters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Clusters) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Clusters) GetDeletionRequested() bool {
	if o == nil {
		return false
	}
	return o.DeletionRequested
}

func (o *Clusters) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Clusters) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Clusters) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *Clusters) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Clusters) GetNodePools() ClustersResultNodePools {
	if o == nil {
		return ClustersResultNodePools{}
	}
	return o.NodePools
}

func (o *Clusters) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *Clusters) GetStatus() *ClustersResultStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// ClustersResultData - Result data.
type ClustersResultData struct {
	// An array of clusters.
	Clusters []Clusters `json:"clusters"`
}

func (o *ClustersResultData) GetClusters() []Clusters {
	if o == nil {
		return []Clusters{}
	}
	return o.Clusters
}

// ClustersResultPagination - Data about the endpoint pagination.
type ClustersResultPagination struct {
	// The number of results returned by this request.
	Count float32 `json:"count"`
	// The cursor to access the next page of results.
	Cursor *string `json:"cursor,omitempty"`
	// Is there another page of results available?
	HasNextPage bool `json:"hasNextPage"`
}

func (o *ClustersResultPagination) GetCount() float32 {
	if o == nil {
		return 0.0
	}
	return o.Count
}

func (o *ClustersResultPagination) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ClustersResultPagination) GetHasNextPage() bool {
	if o == nil {
		return false
	}
	return o.HasNextPage
}

// ClustersResult - Response object.
type ClustersResult struct {
	// Result data.
	Data ClustersResultData `json:"data"`
	// Data about the endpoint pagination.
	Pagination ClustersResultPagination `json:"pagination"`
}

func (o *ClustersResult) GetData() ClustersResultData {
	if o == nil {
		return ClustersResultData{}
	}
	return o.Data
}

func (o *ClustersResult) GetPagination() ClustersResultPagination {
	if o == nil {
		return ClustersResultPagination{}
	}
	return o.Pagination
}
