// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetSubDomainResultData - Result data.
type GetSubDomainResultData struct {
	// The content to set the DNS record to
	Content string `json:"content"`
	// The full domain name with subdomain
	FullName string `json:"fullName"`
	// The subdomain.
	Name string `json:"name"`
	// The record type to use for the DNS record to verify the subdomain - always CNAME for subdomains.
	RecordType string `json:"recordType"`
	// Whether the subdomain has been verified successfully and can be used.
	Verified bool `json:"verified"`
}

func (o *GetSubDomainResultData) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *GetSubDomainResultData) GetFullName() string {
	if o == nil {
		return ""
	}
	return o.FullName
}

func (o *GetSubDomainResultData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetSubDomainResultData) GetRecordType() string {
	if o == nil {
		return ""
	}
	return o.RecordType
}

func (o *GetSubDomainResultData) GetVerified() bool {
	if o == nil {
		return false
	}
	return o.Verified
}

// GetSubDomainResult - Response object.
type GetSubDomainResult struct {
	// Result data.
	Data GetSubDomainResultData `json:"data"`
}

func (o *GetSubDomainResult) GetData() GetSubDomainResultData {
	if o == nil {
		return GetSubDomainResultData{}
	}
	return o.Data
}
