// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RegistryResultAuths - The `auths` data extracted from your Docker config file.
type RegistryResultAuths struct {
}

// RegistryResultProvider - The registry provider associated with this set of credentials.
type RegistryResultProvider string

const (
	RegistryResultProviderDockerhub RegistryResultProvider = "dockerhub"
	RegistryResultProviderGcr       RegistryResultProvider = "gcr"
	RegistryResultProviderGcrEu     RegistryResultProvider = "gcr-eu"
	RegistryResultProviderGcrUs     RegistryResultProvider = "gcr-us"
	RegistryResultProviderGitlab    RegistryResultProvider = "gitlab"
	RegistryResultProviderGithub    RegistryResultProvider = "github"
	RegistryResultProviderCustom    RegistryResultProvider = "custom"
)

func (e RegistryResultProvider) ToPointer() *RegistryResultProvider {
	return &e
}

func (e *RegistryResultProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dockerhub":
		fallthrough
	case "gcr":
		fallthrough
	case "gcr-eu":
		fallthrough
	case "gcr-us":
		fallthrough
	case "gitlab":
		fallthrough
	case "github":
		fallthrough
	case "custom":
		*e = RegistryResultProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RegistryResultProvider: %v", v)
	}
}

// RegistryResultRestrictions - Data about whether the credentials are restricted to certain projects.
type RegistryResultRestrictions struct {
	// An array of projects the credentials are restricted to, if applicable.
	Projects []string `json:"projects"`
	// Whether the credentials are restricted to specific projects.
	Restricted bool `json:"restricted"`
}

func (o *RegistryResultRestrictions) GetProjects() []string {
	if o == nil {
		return []string{}
	}
	return o.Projects
}

func (o *RegistryResultRestrictions) GetRestricted() bool {
	if o == nil {
		return false
	}
	return o.Restricted
}

// RegistryResultData - Result data.
type RegistryResultData struct {
	// The `auths` data extracted from your Docker config file.
	Auths *RegistryResultAuths `json:"auths,omitempty"`
	// Description of the saved credentials.
	Description string `json:"description"`
	// Identifier for the credentials.
	ID string `json:"id"`
	// Name of the saved credentials.
	Name string `json:"name"`
	// The registry provider associated with this set of credentials.
	Provider RegistryResultProvider `json:"provider"`
	// Data about whether the credentials are restricted to certain projects.
	Restrictions RegistryResultRestrictions `json:"restrictions"`
}

func (o *RegistryResultData) GetAuths() *RegistryResultAuths {
	if o == nil {
		return nil
	}
	return o.Auths
}

func (o *RegistryResultData) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *RegistryResultData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RegistryResultData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RegistryResultData) GetProvider() RegistryResultProvider {
	if o == nil {
		return RegistryResultProvider("")
	}
	return o.Provider
}

func (o *RegistryResultData) GetRestrictions() RegistryResultRestrictions {
	if o == nil {
		return RegistryResultRestrictions{}
	}
	return o.Restrictions
}

// RegistryResult - Response object.
type RegistryResult struct {
	// Result data.
	Data RegistryResultData `json:"data"`
}

func (o *RegistryResult) GetData() RegistryResultData {
	if o == nil {
		return RegistryResultData{}
	}
	return o.Data
}
