// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Owner - Details about the repository owner.
type Owner struct {
	// The login of the repository owner.
	Login string `json:"login"`
}

func (o *Owner) GetLogin() string {
	if o == nil {
		return ""
	}
	return o.Login
}

// RepositoriesResultVcsService - Version control provider of the repository.
type RepositoriesResultVcsService string

const (
	RepositoriesResultVcsServiceBitbucket  RepositoriesResultVcsService = "bitbucket"
	RepositoriesResultVcsServiceGitlab     RepositoriesResultVcsService = "gitlab"
	RepositoriesResultVcsServiceGithub     RepositoriesResultVcsService = "github"
	RepositoriesResultVcsServiceSelfHosted RepositoriesResultVcsService = "self-hosted"
)

func (e RepositoriesResultVcsService) ToPointer() *RepositoriesResultVcsService {
	return &e
}

func (e *RepositoriesResultVcsService) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bitbucket":
		fallthrough
	case "gitlab":
		fallthrough
	case "github":
		fallthrough
	case "self-hosted":
		*e = RepositoriesResultVcsService(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RepositoriesResultVcsService: %v", v)
	}
}

// Repos - Details about an accessible repository.
type Repos struct {
	// The login of the linked version control account that can access this repository.
	AccountLogin string `json:"accountLogin"`
	// The full name of the repository.
	FullName string `json:"full_name"`
	// The ID of the repository from the version control provider. This is always returned from the Northflank API as a string for consistency across providers. This value is the numerical ID of a GitHub repository, the numerical ID of a GitLab project, or the UUID of a Bitbucket repository.
	ID string `json:"id"`
	// The name of the repository.
	Name string `json:"name"`
	// Details about the repository owner.
	Owner Owner `json:"owner"`
	// If `vcsService` is `self-hosted`, the ID of the self-hosted provider.
	SelfHostedVcsID *string `json:"selfHostedVcsId,omitempty"`
	// The url of the repository.
	URL string `json:"url"`
	// Version control provider of the repository.
	VcsService RepositoriesResultVcsService `json:"vcsService"`
}

func (o *Repos) GetAccountLogin() string {
	if o == nil {
		return ""
	}
	return o.AccountLogin
}

func (o *Repos) GetFullName() string {
	if o == nil {
		return ""
	}
	return o.FullName
}

func (o *Repos) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Repos) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Repos) GetOwner() Owner {
	if o == nil {
		return Owner{}
	}
	return o.Owner
}

func (o *Repos) GetSelfHostedVcsID() *string {
	if o == nil {
		return nil
	}
	return o.SelfHostedVcsID
}

func (o *Repos) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *Repos) GetVcsService() RepositoriesResultVcsService {
	if o == nil {
		return RepositoriesResultVcsService("")
	}
	return o.VcsService
}

// RepositoriesResultData - Result data.
type RepositoriesResultData struct {
	// A list of accessible repositories.
	Repos []Repos `json:"repos,omitempty"`
}

func (o *RepositoriesResultData) GetRepos() []Repos {
	if o == nil {
		return nil
	}
	return o.Repos
}

// RepositoriesResultPagination - Data about the endpoint pagination.
type RepositoriesResultPagination struct {
	// The number of results returned by this request.
	Count float32 `json:"count"`
	// The cursor to access the next page of results.
	Cursor *string `json:"cursor,omitempty"`
	// Is there another page of results available?
	HasNextPage bool `json:"hasNextPage"`
}

func (o *RepositoriesResultPagination) GetCount() float32 {
	if o == nil {
		return 0.0
	}
	return o.Count
}

func (o *RepositoriesResultPagination) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *RepositoriesResultPagination) GetHasNextPage() bool {
	if o == nil {
		return false
	}
	return o.HasNextPage
}

// RepositoriesResult - Response object.
type RepositoriesResult struct {
	// Result data.
	Data RepositoriesResultData `json:"data"`
	// Data about the endpoint pagination.
	Pagination RepositoriesResultPagination `json:"pagination"`
}

func (o *RepositoriesResult) GetData() RepositoriesResultData {
	if o == nil {
		return RepositoriesResultData{}
	}
	return o.Data
}

func (o *RepositoriesResult) GetPagination() RepositoriesResultPagination {
	if o == nil {
		return RepositoriesResultPagination{}
	}
	return o.Pagination
}
