// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SuccessResultData - Result data.
type SuccessResultData struct {
}

// SuccessResult - Response object.
type SuccessResult struct {
	// Result data.
	Data SuccessResultData `json:"data"`
}

func (o *SuccessResult) GetData() SuccessResultData {
	if o == nil {
		return SuccessResultData{}
	}
	return o.Data
}
