// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateRegistryType4Auths - The `auths` data extracted from your Docker config file.
type UpdateRegistryType4Auths struct {
}

// UpdateRegistryType4Restrictions - Data about whether the credentials are restricted to certain projects.
type UpdateRegistryType4Restrictions struct {
	// An array of projects the credentials are restricted to, if applicable.
	Projects []string `json:"projects,omitempty"`
	// Whether the credentials are restricted to specific projects.
	Restricted bool `json:"restricted"`
}

func (o *UpdateRegistryType4Restrictions) GetProjects() []string {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *UpdateRegistryType4Restrictions) GetRestricted() bool {
	if o == nil {
		return false
	}
	return o.Restricted
}

// UpdateRegistryType4 - Validate with a docker config file.
type UpdateRegistryType4 struct {
	// The `auths` data extracted from your Docker config file.
	Auths UpdateRegistryType4Auths `json:"auths"`
	// Description of the credentials.
	Description *string `json:"description,omitempty"`
	// Data about whether the credentials are restricted to certain projects.
	Restrictions *UpdateRegistryType4Restrictions `json:"restrictions,omitempty"`
}

func (o *UpdateRegistryType4) GetAuths() UpdateRegistryType4Auths {
	if o == nil {
		return UpdateRegistryType4Auths{}
	}
	return o.Auths
}

func (o *UpdateRegistryType4) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateRegistryType4) GetRestrictions() *UpdateRegistryType4Restrictions {
	if o == nil {
		return nil
	}
	return o.Restrictions
}
