// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/utils"
)

// UpdateIntegrationRequestCredentials - Cloud provider credential input, required fields dependent on which provider is chosen.
type UpdateIntegrationRequestCredentials struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// AWS access key.
	AccessKey *string `json:"accessKey,omitempty"`
	// DO API key.
	APIKey *string `json:"apiKey,omitempty"`
	// Contents of a GCP key file.
	KeyfileJSON *string `json:"keyfileJson,omitempty"`
	// AWS secret key.
	SecretKey *string `json:"secretKey,omitempty"`
}

func (u UpdateIntegrationRequestCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateIntegrationRequestCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateIntegrationRequestCredentials) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *UpdateIntegrationRequestCredentials) GetAccessKey() *string {
	if o == nil {
		return nil
	}
	return o.AccessKey
}

func (o *UpdateIntegrationRequestCredentials) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *UpdateIntegrationRequestCredentials) GetKeyfileJSON() *string {
	if o == nil {
		return nil
	}
	return o.KeyfileJSON
}

func (o *UpdateIntegrationRequestCredentials) GetSecretKey() *string {
	if o == nil {
		return nil
	}
	return o.SecretKey
}

type UpdateIntegrationRequest struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// Cloud provider credential input, required fields dependent on which provider is chosen.
	Credentials UpdateIntegrationRequestCredentials `json:"credentials"`
	// The description of the integration.
	Description *string `json:"description,omitempty"`
}

func (u UpdateIntegrationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateIntegrationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateIntegrationRequest) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *UpdateIntegrationRequest) GetCredentials() UpdateIntegrationRequestCredentials {
	if o == nil {
		return UpdateIntegrationRequestCredentials{}
	}
	return o.Credentials
}

func (o *UpdateIntegrationRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
