// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/northflank-go/v2/pkg/utils"
	"time"
)

// UpdateIntegrationResultCredentials - Cloud provider credential input, required fields dependent on which provider is chosen.
type UpdateIntegrationResultCredentials struct {
	// AWS access key.
	AccessKey *string `json:"accessKey,omitempty"`
	// DO API key.
	APIKey *string `json:"apiKey,omitempty"`
	// Contents of a GCP key file.
	KeyfileJSON *string `json:"keyfileJson,omitempty"`
	// AWS secret key.
	SecretKey *string `json:"secretKey,omitempty"`
}

func (o *UpdateIntegrationResultCredentials) GetAccessKey() *string {
	if o == nil {
		return nil
	}
	return o.AccessKey
}

func (o *UpdateIntegrationResultCredentials) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *UpdateIntegrationResultCredentials) GetKeyfileJSON() *string {
	if o == nil {
		return nil
	}
	return o.KeyfileJSON
}

func (o *UpdateIntegrationResultCredentials) GetSecretKey() *string {
	if o == nil {
		return nil
	}
	return o.SecretKey
}

// UpdateIntegrationResultData - Result data.
type UpdateIntegrationResultData struct {
	// The time the integration was created.
	CreatedAt time.Time `json:"createdAt"`
	// Cloud provider credential input, required fields dependent on which provider is chosen.
	Credentials UpdateIntegrationResultCredentials `json:"credentials"`
	// A short description of the integration.
	Description *string `json:"description,omitempty"`
	// Identifier for the integration.
	ID string `json:"id"`
	// The name of the integration.
	Name string `json:"name"`
}

func (u UpdateIntegrationResultData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateIntegrationResultData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateIntegrationResultData) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *UpdateIntegrationResultData) GetCredentials() UpdateIntegrationResultCredentials {
	if o == nil {
		return UpdateIntegrationResultCredentials{}
	}
	return o.Credentials
}

func (o *UpdateIntegrationResultData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateIntegrationResultData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateIntegrationResultData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

// UpdateIntegrationResult - Response object.
type UpdateIntegrationResult struct {
	// Result data.
	Data UpdateIntegrationResultData `json:"data"`
}

func (o *UpdateIntegrationResult) GetData() UpdateIntegrationResultData {
	if o == nil {
		return UpdateIntegrationResultData{}
	}
	return o.Data
}
