// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateRegistryType4Auths - The `auths` data extracted from your Docker config file.
type UpdateRegistryType4Auths struct {
}

// UpdateRegistryType4Restrictions - Data about whether the credentials are restricted to certain projects.
type UpdateRegistryType4Restrictions struct {
	// An array of projects the credentials are restricted to, if applicable.
	Projects []string `json:"projects,omitempty"`
	// Whether the credentials are restricted to specific projects.
	Restricted bool `json:"restricted"`
}

func (o *UpdateRegistryType4Restrictions) GetProjects() []string {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *UpdateRegistryType4Restrictions) GetRestricted() bool {
	if o == nil {
		return false
	}
	return o.Restricted
}

type UpdateRegistryType2 struct {
	// Description of the credentials.
	Description *string `json:"description,omitempty"`
	// Password, Personal Access Token, or API key for the container registry.
	Password string `json:"password"`
	// Custom url for the container registry. Only usable (and required) when `provider` is `custom`.
	RegistryURL *string `json:"registryUrl,omitempty"`
	// Data about whether the credentials are restricted to certain projects.
	Restrictions *UpdateRegistryType2Restrictions `json:"restrictions,omitempty"`
	// Username for the container registry.
	Username string `json:"username"`
}

func (o *UpdateRegistryType2) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateRegistryType2) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *UpdateRegistryType2) GetRegistryURL() *string {
	if o == nil {
		return nil
	}
	return o.RegistryURL
}

func (o *UpdateRegistryType2) GetRestrictions() *UpdateRegistryType2Restrictions {
	if o == nil {
		return nil
	}
	return o.Restrictions
}

func (o *UpdateRegistryType2) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
