// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/northflank-go/pkg/utils"
	"time"
)

// UpdateClusterResultDataNodePoolsAutoscaling - Auto scaling settings to use for the node pool. Requires that the cloud provider supports this feature.
type UpdateClusterResultDataNodePoolsAutoscaling struct {
	Enabled *bool  `default:"false" json:"enabled"`
	Max     *int64 `json:"max,omitempty"`
	Min     *int64 `json:"min,omitempty"`
}

func (u UpdateClusterResultDataNodePoolsAutoscaling) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateClusterResultDataNodePoolsAutoscaling) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateClusterResultDataNodePoolsAutoscaling) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *UpdateClusterResultDataNodePoolsAutoscaling) GetMax() *int64 {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *UpdateClusterResultDataNodePoolsAutoscaling) GetMin() *int64 {
	if o == nil {
		return nil
	}
	return o.Min
}

// UpdateClusterResultDataNodePoolsLabels - Set of label keys and values that can be used to determine scheduling via resource tags.
type UpdateClusterResultDataNodePoolsLabels struct {
}

type UpdateClusterResultDataNodePools struct {
	// Auto scaling settings to use for the node pool. Requires that the cloud provider supports this feature.
	Autoscaling *UpdateClusterResultDataNodePoolsAutoscaling `json:"autoscaling,omitempty"`
	// Zones in which the node pool should be provisioned.
	AvailabilityZones []string `json:"availabilityZones,omitempty"`
	// Disk size in GB
	DiskSize int64 `json:"diskSize"`
	// The disk type to use.
	DiskType *string `json:"diskType,omitempty"`
	// ID of existing node pool. Must be passed when modifying existing node pools. Not relevant for new node pools
	ID *string `json:"id,omitempty"`
	// Set of label keys and values that can be used to determine scheduling via resource tags.
	Labels *UpdateClusterResultDataNodePoolsLabels `json:"labels,omitempty"`
	// Number of nodes to the node pool should be provisioned with.
	NodeCount int64 `json:"nodeCount"`
	// Machine type to be used by the node pool.
	NodeType string `json:"nodeType"`
	// Configures node pool with preemptible / spot instances if enabled.
	Preemptible *bool `default:"false" json:"preemptible"`
	// When 'provider' is 'azure', at least one system node pool is required per cluster.
	SystemPool *bool `json:"systemPool,omitempty"`
}

func (u UpdateClusterResultDataNodePools) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateClusterResultDataNodePools) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateClusterResultDataNodePools) GetAutoscaling() *UpdateClusterResultDataNodePoolsAutoscaling {
	if o == nil {
		return nil
	}
	return o.Autoscaling
}

func (o *UpdateClusterResultDataNodePools) GetAvailabilityZones() []string {
	if o == nil {
		return nil
	}
	return o.AvailabilityZones
}

func (o *UpdateClusterResultDataNodePools) GetDiskSize() int64 {
	if o == nil {
		return 0
	}
	return o.DiskSize
}

func (o *UpdateClusterResultDataNodePools) GetDiskType() *string {
	if o == nil {
		return nil
	}
	return o.DiskType
}

func (o *UpdateClusterResultDataNodePools) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UpdateClusterResultDataNodePools) GetLabels() *UpdateClusterResultDataNodePoolsLabels {
	if o == nil {
		return nil
	}
	return o.Labels
}

func (o *UpdateClusterResultDataNodePools) GetNodeCount() int64 {
	if o == nil {
		return 0
	}
	return o.NodeCount
}

func (o *UpdateClusterResultDataNodePools) GetNodeType() string {
	if o == nil {
		return ""
	}
	return o.NodeType
}

func (o *UpdateClusterResultDataNodePools) GetPreemptible() *bool {
	if o == nil {
		return nil
	}
	return o.Preemptible
}

func (o *UpdateClusterResultDataNodePools) GetSystemPool() *bool {
	if o == nil {
		return nil
	}
	return o.SystemPool
}

type UpdateClusterResultDataStatusState struct {
	State          *string    `json:"state,omitempty"`
	TransitionTime *time.Time `json:"transitionTime,omitempty"`
}

func (u UpdateClusterResultDataStatusState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateClusterResultDataStatusState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateClusterResultDataStatusState) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *UpdateClusterResultDataStatusState) GetTransitionTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.TransitionTime
}

type UpdateClusterResultDataStatus struct {
	NextUpdateAfter *time.Time                          `json:"nextUpdateAfter,omitempty"`
	State           *UpdateClusterResultDataStatusState `json:"state,omitempty"`
}

func (u UpdateClusterResultDataStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateClusterResultDataStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateClusterResultDataStatus) GetNextUpdateAfter() *time.Time {
	if o == nil {
		return nil
	}
	return o.NextUpdateAfter
}

func (o *UpdateClusterResultDataStatus) GetState() *UpdateClusterResultDataStatusState {
	if o == nil {
		return nil
	}
	return o.State
}

// UpdateClusterResultData - Result data.
type UpdateClusterResultData struct {
	// The time the cluster was created.
	CreatedAt time.Time `json:"createdAt"`
	// Indicates if provider resource deletion has been requested by the user.
	DeletionRequested bool `json:"deletionRequested"`
	// A short description of the cluster.
	Description *string `json:"description,omitempty"`
	// Identifier for the cluster.
	ID string `json:"id"`
	// ID of the provider integration used by this cluster.
	IntegrationID string `json:"integrationId"`
	// The name of the cluster.
	Name      string                           `json:"name"`
	NodePools UpdateClusterResultDataNodePools `json:"nodePools"`
	// The cloud provider to which this cluster belongs to.
	Provider *string                        `json:"provider,omitempty"`
	Status   *UpdateClusterResultDataStatus `json:"status,omitempty"`
}

func (u UpdateClusterResultData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateClusterResultData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateClusterResultData) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *UpdateClusterResultData) GetDeletionRequested() bool {
	if o == nil {
		return false
	}
	return o.DeletionRequested
}

func (o *UpdateClusterResultData) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateClusterResultData) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateClusterResultData) GetIntegrationID() string {
	if o == nil {
		return ""
	}
	return o.IntegrationID
}

func (o *UpdateClusterResultData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateClusterResultData) GetNodePools() UpdateClusterResultDataNodePools {
	if o == nil {
		return UpdateClusterResultDataNodePools{}
	}
	return o.NodePools
}

func (o *UpdateClusterResultData) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *UpdateClusterResultData) GetStatus() *UpdateClusterResultDataStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// UpdateClusterResult - Response object.
type UpdateClusterResult struct {
	// Result data.
	Data UpdateClusterResultData `json:"data"`
}

func (o *UpdateClusterResult) GetData() UpdateClusterResultData {
	if o == nil {
		return UpdateClusterResultData{}
	}
	return o.Data
}
