// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateRegistryType3Keyfile - Contents of `keyfile.json`, used to authenticate with Google Container Registry.
type UpdateRegistryType3Keyfile struct {
}

// UpdateRegistryType3Restrictions - Data about whether the credentials are restricted to certain projects.
type UpdateRegistryType3Restrictions struct {
	// An array of projects the credentials are restricted to, if applicable.
	Projects []string `json:"projects,omitempty"`
	// Whether the credentials are restricted to specific projects.
	Restricted bool `json:"restricted"`
}

func (o *UpdateRegistryType3Restrictions) GetProjects() []string {
	if o == nil {
		return nil
	}
	return o.Projects
}

func (o *UpdateRegistryType3Restrictions) GetRestricted() bool {
	if o == nil {
		return false
	}
	return o.Restricted
}

// UpdateRegistryType3 - Authenticate with a `keyfile.json`. Used for authenticating with Google Container Registry.
type UpdateRegistryType3 struct {
	// Description of the credentials.
	Description *string `json:"description,omitempty"`
	// Contents of `keyfile.json`, used to authenticate with Google Container Registry.
	Keyfile UpdateRegistryType3Keyfile `json:"keyfile"`
	// Custom url for the container registry. Only usable (and required) when `provider` is `custom`.
	RegistryURL *string `json:"registryUrl,omitempty"`
	// Data about whether the credentials are restricted to certain projects.
	Restrictions *UpdateRegistryType3Restrictions `json:"restrictions,omitempty"`
}

func (o *UpdateRegistryType3) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateRegistryType3) GetKeyfile() UpdateRegistryType3Keyfile {
	if o == nil {
		return UpdateRegistryType3Keyfile{}
	}
	return o.Keyfile
}

func (o *UpdateRegistryType3) GetRegistryURL() *string {
	if o == nil {
		return nil
	}
	return o.RegistryURL
}

func (o *UpdateRegistryType3) GetRestrictions() *UpdateRegistryType3Restrictions {
	if o == nil {
		return nil
	}
	return o.Restrictions
}
