// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VCSTokenResultDataVCSService - VCS provider the token belongs to.
type VCSTokenResultDataVCSService string

const (
	VCSTokenResultDataVCSServiceBitbucket  VCSTokenResultDataVCSService = "bitbucket"
	VCSTokenResultDataVCSServiceGitlab     VCSTokenResultDataVCSService = "gitlab"
	VCSTokenResultDataVCSServiceGithub     VCSTokenResultDataVCSService = "github"
	VCSTokenResultDataVCSServiceSelfHosted VCSTokenResultDataVCSService = "self-hosted"
)

func (e VCSTokenResultDataVCSService) ToPointer() *VCSTokenResultDataVCSService {
	return &e
}

func (e *VCSTokenResultDataVCSService) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bitbucket":
		fallthrough
	case "gitlab":
		fallthrough
	case "github":
		fallthrough
	case "self-hosted":
		*e = VCSTokenResultDataVCSService(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VCSTokenResultDataVCSService: %v", v)
	}
}

// VCSTokenResultData - Result data.
type VCSTokenResultData struct {
	// Installation ID of the GitHub installation the token belongs to (GitHub only)
	InstallationID *int64 `json:"installationId,omitempty"`
	// Installation token (GitHub only).
	InstallationToken *string `json:"installationToken,omitempty"`
	// OAuth token.
	Token string `json:"token"`
	// VCS provider the token belongs to.
	VcsService VCSTokenResultDataVCSService `json:"vcsService"`
}

func (o *VCSTokenResultData) GetInstallationID() *int64 {
	if o == nil {
		return nil
	}
	return o.InstallationID
}

func (o *VCSTokenResultData) GetInstallationToken() *string {
	if o == nil {
		return nil
	}
	return o.InstallationToken
}

func (o *VCSTokenResultData) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *VCSTokenResultData) GetVcsService() VCSTokenResultDataVCSService {
	if o == nil {
		return VCSTokenResultDataVCSService("")
	}
	return o.VcsService
}

// VCSTokenResult - Response object.
type VCSTokenResult struct {
	// Result data.
	Data VCSTokenResultData `json:"data"`
}

func (o *VCSTokenResult) GetData() VCSTokenResultData {
	if o == nil {
		return VCSTokenResultData{}
	}
	return o.Data
}
